### ISSUE TITLE
Error when re-running an analysis

### ISSUE THREAD

**Issue by williamdlees** [airr-community/rep-cred#9] opened 2022-01-30 15:00 UTC
Once you have run one analysis in repcred, attempting to run a second analysis results in the message 'Warning: Error in setwd: cannot change working directory'.

**Comment by GeorginaLeslie** [comment] 2022-03-28 18:44
This looks to actually be fixed already. If the issue is still occurring I will take another look.

**Comment by ssnn-airr** [comment] 2022-07-06 15:26
I should have closed this when I fixed it. I think the issue was the use of setwd() (commit ddb970a)

**Closed as completed by ssnn-airr** 2022-07-06 15:26 UTC
Labels: bug
